services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./bot/.env

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    container_name: scheduler
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./scheduler/.env

volumes:
  mongodb_data:
