services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - app_network

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./bot/.env
    networks:
      - app_network

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    container_name: scheduler
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - ./scheduler/.env
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network


volumes:
  mongodb_data:
  redis_data:

networks:
  app_network:
    driver: bridge
